GET http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDBjNDRiZWQ2ZjM0ZDI1MjAzZTA2OGQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2NzkxMjc2NzQsImV4cCI6MTY3OTEzMTI3NH0.uPC5y6GaTV5BpzSEo8hA36poLSKvHB9IkA6jwrmSZK8 HTTP/1.1